### ISSUE TITLE
audo-dependencies update will remove arch specific binaries

### ISSUE THREAD

**Issue by Josh5** [lsellens/script.module.audo-dependencies#1]
If audo-dependencies addon is updated, we need to restart SAB, SB, CP & HP. The update removes the binaries. Restarting the addon should fix this.

EDIT: I think the issue I experianced lies elsewhere. Please disregard the above

**Comment by Josh5** [comment]
Found the issue...
audo-dependencies' default.py is being executed too quickly. 
We either need to add another sleep, perhaps another 5 sec before running "xbmc.executebuiltin('XBMC.RunScript(%s)' % xbmc.translatePath(**dependancies** + '/default.py'), True)".
Or we need to come up with a way to better detect when xbmc has finished unpacking the audo-dependencies addon. 

From my logs i can see it takes about 9 sec for xbmc to unpack audo-dependencies on an armv7 machine (raspi will no doubt be slower). The "default.py" is always executed within 5 sec.

I'll put together a fix in a bit...

**Comment by lsellens** [comment]
Do you know if unzip extracts in a particular order? It seems to extract the changelog.txt last when I test but don't know if it always will on all systems. checking for that file or just adding a sleep is all I can think of...

**Comment by Josh5** [comment]
What about some sort of checksum of the whole folder?

**Comment by Josh5** [comment]
Or another idea is to count the number of files in the dir. Sleep 5 sec then count them again. If nothing has changed, then the zip has finished extracting.
I can write this...
